### DISCUSSION TITLE
为使用 Docker 部署节点进行网络上行限速的一种解决办法

### DISCUSSION THREAD

**Discussion by SnowballXueQiu** [bangbang93/openbmclapi#47] [General]
## 前言

- 对于一些使用家庭宽带或云服务器部署本节点的用户, 可能会为防止运营商或云服务器商由于短时间内产生大量上行流量而进行限制或封禁, 所以我们要采取一些措施, 来限制本节点上行速率, 以实现安全地部署本节点.

## 步骤

0. **确保您的节点可以正常使用**

1. 更改您的 `docker-compose.yml` 文件:

    - 您需要在原文件的基础上, 添加 `network` 参数

        ```yaml
        # docker-compose.yml
        version: '3'

        networks:
          openbmclapi:

        services:
          openbmclapi:
            image: bangbang93/openbmclapi
            environment:
              CLUSTER_ID: ${CLUSTER_ID}
              CLUSTER_SECRET: ${CLUSTER_SECRET}
              CLUSTER_PUBLIC_PORT: 4000
              TZ: Asia/Shanghai
        #      CLUSTER_IP: ''
            volumes:
              - ./cache:/opt/openbmclapi/cache
            ports:
              - "4000:4000"
            restart: always
            logging:
              driver: 'json-file'
              options:
                max-size: '100m'
                max-file: '10'
            networks:
              openbmclapi: {}
        ```
    
2. 使用 `wondershaper` 程序进行限速

    - 程序文档: [`wondershaper`](https://manpages.ubuntu.com/manpages/xenial/man8/wondershaper.8.html)

    1. 获取 `container_id`

        ```bash
        docker ps -a

        输出: 9dc1b9328878 bangbang93/openbmclapi "docker-entrypoint.s…" 1 hours ago Up 1 hours 0.0.0.0:4000
        ```

        其中 `9dc1b932887` 即为本容器的 `container_id`

    2. 安装并使用 `wondershaper`

        ```bash
        apt-get update
        apt-get install wondershaper

        wondershaper <网卡> <下行速度> <上行速度>
        ```

        其中, 网卡为 `'br-' + '您的 container_id'`, 例如 `br-9dc1b9328878`; 下行速度和上行速度单位为 `Kbits/s, 请自行根据需求填写

        - 示例, 为节点限制上下行均为 10 Mib/s 速度:

            ```bash
            wondershaper br-9dc1b9328878 80000 80000
            ```

        **那么, 现在就大功告成了!!**

    3. 关闭限制方法

        ```bash
        wondershaper clear <网卡>
        ```
